### ISSUE TITLE
Location based Culver’s lookup

### ISSUE THREAD

**Issue by jbeardsleyhey** [jpchip/mke-frozen-treats#1]
Love to have the Culver's Flavor of the Day based on either (or all):

- radius of current device location (best effort)
  - e.g., within 5 miles of device
- radius of a zip code I supply
  - save my preference in local storage
- let me pick my favorite culvers
  - save my preferences in local storage

Great project BTW, keep it up! 💯

**Comment by jpchip** [comment]
Oh i really like the idea of favorites, could apply to all the places, not just Culver's! Would let Users filter down to just the locations they really care about, hiding the rest, stored in localstorage.

I think I will go that route. Thanks for the idea!

**Comment by jpchip** [comment]
Favorites added. @jbeardsleyhey, I will add more Culver's locations now! Do you have any you me to start with?

**Comment by jbeardsleyhey** [comment]
Shorewood, Glendale, Mequon.

**Comment by jpchip** [comment]
Added more Culver's locations. Just let me know if you need any more.
